(deftheme zenburn
  "Created 2016-12-22.")

(custom-theme-set-variables
 'zenburn
 '(ansi-color-names-vector ["#3F3F3F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"]))

(custom-theme-set-faces
 'zenburn
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(cursor ((t (:foreground "#DCDCCC" :background "white"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :bold t))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#383838"))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(compilation-info ((t (:foreground "#BFEBBF" :underline t))))
 '(compilation-line-number ((t (:foreground "#F0DFAF"))))
 '(compilation-mode-line-exit ((t (:foreground "#9FC59F" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#CC9393" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#F0DFAF" :weight bold))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#2B2B2B"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(region ((t (:background "OliveDrab4"))))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(ace-jump-face-background ((t (:foreground "#656555" :background "#3F3F3F" :inverse-video nil))))
 '(ace-jump-face-foreground ((t (:foreground "#9FC59F" :background "#3F3F3F" :inverse-video nil))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#BC8383" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(linum ((t (:foreground "#9FC59F" :background "#3F3F3F"))))
 '(show-paren-mismatch ((t (:foreground "#9C6363" :background "#3F3F3F" :weight bold))))
 '(show-paren-match ((t (:foreground "#7CB8BB" :background "#3F3F3F" :weight bold))))
 '(which-func ((t (:foreground "#BFEBBF"))))
 '(default ((t (:foreground "#DCDCCC" :background "#3F3F3F")))))

(provide-theme 'zenburn)
